### ISSUE TITLE
[ALGO] Bug report on move piece

### ISSUE THREAD

**Issue by plumsirawit** [closedfish/closedfish#109]
On `r1bqkb1r/ppppppp1/8/n2P3p/8/5N2/PP2PPPP/RNBQKB1R w KQkq - 0 1`, cannot do move `c1d2`.

**Comment by Yoshimi-Theophile** [comment]
Inputting the same board directly on CFBoard yields no error.

**Comment by plumsirawit** [comment]
Use evidence from `bug-on-cligame` instead.
